topdir := $(shell i=. ; for c in 0 1 2 3 4 5 6 7 8; do [ ! -f $$i/.chimas_top ] && i=$$i/..; done; echo $$i)#
TOPDIR=$(shell realpath $(topdir))

#
# Enable parallelization
# 
launch:
	$(MAKE) -j10 -C .. set-opt 
	../py/launch.py

.force:


