
#
#
#
netcdf: 
	cd /opt && tar zxf /opt/hdf5-1.14.6.tar.gz 
	 cd /opt/hdf5*/ && mkdir build && cd build && \
		 cmake  -DCMAKE_INSTALL_PREFIX=/usr/local \
				-DBUILD_SHARED_LIBS=ON \
				-DHDF5_ENABLE_PARALLEL=ON \
				-DHDF5_ENABLE_HL=ON \
				-DHDF5_BUILD_CPP_LIB=OFF \
				-DHDF5_BUILD_EXAMPLES=OFF \
				-DHDF5_BUILD_TOOLS=ON \
				-DCMAKE_C_COMPILER=mpicc \
				-DCMAKE_CXX_COMPILER=mpicxx .. && \
	make -j10 && make install
